import Link from "next/link";

export default function TermsOfServicePage() {
    return (
        <main className="sw-legal">
            <article>
                <div className="space-y-8">
                    <div className="mb-8">
                        <Link
                            href="/"
                            className="sw-button-secondary w-fit"
                        >
                            Back to home
                        </Link>
                    </div>

                    <h1>Terms of Service</h1>
                    <p>
                        Last Updated: November 1, 2025
                    </p>

                    <div>
                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-slate-900 mb-4">1. Acceptance of Terms</h2>
                            <p className="text-slate-700 mb-4">
                                By accessing and using StockWin (&quot;Service&quot;, &quot;Platform&quot;), you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-slate-900 mb-4">2. Description of Service</h2>
                            <p className="text-slate-700 mb-4">
                                StockWin provides AI-powered stock and cryptocurrency price predictions generated by our proprietary forecasting stack. Our Service includes:
                            </p>
                            <ul className="list-disc pl-6 text-slate-700 mb-4 space-y-2">
                                <li>24-hour price forecasts for pre-selected stocks and cryptocurrencies</li>
                                <li>Confidence intervals and risk assessment metrics</li>
                                <li>Real-time data updates and analysis</li>
                                <li>Portfolio tracking and prediction history</li>
                            </ul>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-slate-900 mb-4">3. Investment Disclaimer</h2>
                            <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-4">
                                <p className="text-slate-700 font-semibold mb-2">IMPORTANT NOTICE:</p>
                                <p className="text-slate-700">
                                    StockWin provides informational predictions and analysis only. Our predictions are NOT financial advice, investment recommendations, or guarantees of future performance. All investment decisions are solely your responsibility.
                                </p>
                            </div>
                            <p className="text-slate-700 mb-4">
                                You acknowledge and understand that:
                            </p>
                            <ul className="list-disc pl-6 text-slate-700 mb-4 space-y-2">
                                <li>Trading stocks and cryptocurrencies involves substantial risk of loss</li>
                                <li>Past performance does not guarantee future results</li>
                                <li>AI predictions may be inaccurate or incorrect</li>
                                <li>You should consult with a qualified financial advisor before making investment decisions</li>
                                <li>StockWin is not a registered investment advisor, broker-dealer, or financial institution</li>
                            </ul>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-slate-900 mb-4">4. User Accounts and Responsibilities</h2>
                            <p className="text-slate-700 mb-4">
                                When you create an account with StockWin, you agree to:
                            </p>
                            <ul className="list-disc pl-6 text-slate-700 mb-4 space-y-2">
                                <li>Provide accurate, current, and complete information</li>
                                <li>Maintain the security of your password and account</li>
                                <li>Accept responsibility for all activities under your account</li>
                                <li>Notify us immediately of any unauthorized use</li>
                                <li>Not share your account with others</li>
                            </ul>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-slate-900 mb-4">5. Subscription and Payment</h2>
                            <p className="text-slate-700 mb-4">
                                StockWin offers both free and paid subscription tiers:
                            </p>
                            <ul className="list-disc pl-6 text-slate-700 mb-4 space-y-2">
                                <li><strong>Free Tier:</strong> Access to limited predictions for pre-selected assets</li>
                                <li><strong>PRO Tier:</strong> Full access to all predictions and premium features</li>
                            </ul>
                            <p className="text-slate-700 mb-4">
                                For paid subscriptions:
                            </p>
                            <ul className="list-disc pl-6 text-slate-700 mb-4 space-y-2">
                                <li>Subscriptions are billed on a recurring basis (monthly or annually)</li>
                                <li>You may cancel at any time; cancellation takes effect at the end of the current billing period</li>
                                <li>No refunds for partial months or unused portions</li>
                                <li>Prices may change with 30 days notice to existing subscribers</li>
                            </ul>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-slate-900 mb-4">6. Intellectual Property</h2>
                            <p className="text-slate-700 mb-4">
                                All content, features, and functionality of the Service, including but not limited to text, graphics, logos, software, AI models, and data, are owned by StockWin or its licensors and protected by intellectual property laws.
                            </p>
                            <p className="text-slate-700 mb-4">
                                You may not:
                            </p>
                            <ul className="list-disc pl-6 text-slate-700 mb-4 space-y-2">
                                <li>Copy, modify, distribute, or reverse-engineer our Service</li>
                                <li>Use automated systems to scrape or extract data</li>
                                <li>Resell or commercialize our predictions without permission</li>
                                <li>Remove copyright or proprietary notices</li>
                            </ul>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-slate-900 mb-4">7. Limitation of Liability</h2>
                            <p className="text-slate-700 mb-4">
                                TO THE MAXIMUM EXTENT PERMITTED BY LAW:
                            </p>
                            <ul className="list-disc pl-6 text-slate-700 mb-4 space-y-2">
                                <li>StockWin is provided &quot;AS IS&quot; without warranties of any kind</li>
                                <li>We do not guarantee accuracy, reliability, or availability of predictions</li>
                                <li>We are not liable for any investment losses or damages resulting from use of our Service</li>
                                <li>Our total liability shall not exceed the amount you paid for the Service in the past 12 months</li>
                            </ul>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-slate-900 mb-4">8. Prohibited Uses</h2>
                            <p className="text-slate-700 mb-4">
                                You agree not to:
                            </p>
                            <ul className="list-disc pl-6 text-slate-700 mb-4 space-y-2">
                                <li>Use the Service for illegal purposes or to violate any laws</li>
                                <li>Attempt to gain unauthorized access to our systems</li>
                                <li>Interfere with or disrupt the Service</li>
                                <li>Transmit viruses, malware, or harmful code</li>
                                <li>Impersonate others or provide false information</li>
                                <li>Harass, abuse, or harm other users</li>
                            </ul>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-slate-900 mb-4">9. Termination</h2>
                            <p className="text-slate-700 mb-4">
                                We may terminate or suspend your account and access to the Service immediately, without prior notice, for any reason, including if you breach these Terms. Upon termination, your right to use the Service will cease immediately.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-slate-900 mb-4">10. Changes to Terms</h2>
                            <p className="text-slate-700 mb-4">
                                We reserve the right to modify these Terms at any time. We will notify users of material changes via email or through the Service. Continued use of the Service after changes constitutes acceptance of the modified Terms.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-slate-900 mb-4">11. Governing Law</h2>
                            <p className="text-slate-700 mb-4">
                                These Terms shall be governed by and construed in accordance with the laws of the jurisdiction where StockWin operates, without regard to conflict of law provisions.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-slate-900 mb-4">12. Contact Information</h2>
                            <p className="text-slate-700 mb-4">
                                If you have questions about these Terms, please contact us at:
                            </p>
                            <p className="text-slate-700">
                                Email: stockwin.win@proton.me<br />
                                Website: www.stockwin.win
                            </p>
                        </section>
                    </div>
                </div>
            </article>
        </main>
    );
}
